#ifndef RUTASSPRITES_H_INCLUDED
#define RUTASSPRITES_H_INCLUDED

//Constantes de todas las rutas de los sprites usados por personajes

//Capitan America
char const *capitanAmericaSprites[10] =
{
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_0.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_A1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_A2.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_A3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_A4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_D.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/CAPTAIN_AMERICA/Captain_America_D2.png"
};

//Dare Devil
char const *dareDevilSprites[10] =
{
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_0.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_A1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_A2.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_A3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_A4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_D.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/DARE_DEVIL/Dare_Devil_D2.png"
};

//Iron Man
char const *ironManSprites[10] =
{
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_0.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_A1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_A2.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_A3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_A4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_D.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/IRON_MAN/Iron_Man_D2.png"
};

//Spider Man
char const *spiderManSprites[10] =
{
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_0.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_A1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_A2.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_A3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_A4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_D.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/SPIDER_MAN/Spider_Man_D2.png"
};

//Star Lord
char const *starLordSprites[10] =
{
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_0.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_A1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_A2.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_A3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_A4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_D.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/STAR_LORD/Star_Lord_D2.png"
};

char const *thorSprites[10] =
{
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_0.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_A1.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_A2.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_A3.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_A4.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_D.png",
    "RESOURCES/IMAGES/SPRITES/CHARACTERS/THOR/Thor_D2.png"
};



#endif // RUTASSPRITES_H_INCLUDED
